spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: a12345678
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    